<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Loads Amazon star ratings and review counts onto existing products.
 *
 *     php artisan db:seed --class=AmazonRatingsSeeder
 *
 * Data comes from database/data/amazon-ratings.csv (generated by amazon_ratings.py at the
 * repo root, reviewed by hand). Rows are matched by product id. Products not in the file
 * are left untouched, so ones without an Amazon rating keep rating = NULL. Safe to re-run.
 */
class AmazonRatingsSeeder extends Seeder
{
    public function run(): void
    {
        $file = fopen(database_path('data/amazon-ratings.csv'), 'r');
        $header = fgetcsv($file);
        $updated = 0;

        while (($row = fgetcsv($file)) !== false) {
            $r = array_combine($header, $row);
            $updated += DB::table('products')->where('id', $r['id'])->update([
                'rating'       => $r['rating'],
                'review_count' => $r['review_count'] !== '' ? $r['review_count'] : null,
            ]);
        }
        fclose($file);

        $this->command->info("Amazon ratings: {$updated} products updated.");
    }
}
